/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const NewTaskLazyImport = createFileRoute('/new-task')()

// Create/Update Routes

const NewTaskLazyRoute = NewTaskLazyImport.update({
  id: '/new-task',
  path: '/new-task',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/new-task.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new-task': {
      id: '/new-task'
      path: '/new-task'
      fullPath: '/new-task'
      preLoaderRoute: typeof NewTaskLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-task'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-task'
  id: '__root__' | '/' | '/new-task'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewTaskLazyRoute: typeof NewTaskLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewTaskLazyRoute: NewTaskLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new-task"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new-task": {
      "filePath": "new-task.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
